version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "monthly"
- package-ecosystem: "maven"
  directory: "/src/test/resources/test-project-exception/"
  schedule:
    interval: "monthly"
- package-ecosystem: "maven"
  directory: "/src/test/resources/test-project-print/"
  schedule:
    interval: "monthly"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
