name: Continuous Integration

on:
  push:
    branches-ignore:
      - master
  schedule:
    - cron: '6 22 22 * *'

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      env:
        REVISION: ${{ github.sha }}
      run: |
        ./mvnw \
          --batch-mode \
          -Dsha1="${GITHUB_SHA}" \
          -Drevision="${REVISION}" \
          verify
        mkdir target/artifacts
        cp target/mvnx-* target/artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: mvnx-${{ github.job }}-${{ github.sha }}
        path: target/artifacts
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      env:
        REVISION: ${{ github.sha }}
      run: |
        ./mvnw \
          --batch-mode \
          -Dsha1="${GITHUB_SHA}" \
          -Drevision="${REVISION}" \
          verify
        mkdir target/artifacts
        cp target/mvnx-* target/artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: mvnx-${{ github.job }}-${{ github.sha }}
        path: target/artifacts
  windows:
    runs-on: windows-latest
    env:
      USER: runner
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: .m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      shell: cmd
      env:
        REVISION: ${{ github.sha }}
      run: |
        call .\mvnw --batch-mode -Dsha1="%GITHUB_SHA%" -Drevision="%REVISION%" verify
        mkdir target\artifacts
        copy target\mvnx-* target\artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: mvnx-${{ github.job }}-${{ github.sha }}
        path: target/artifacts
  deploy:
    needs: [macos, linux, windows]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Publish to GitHub Packages Apache Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REVISION: ${{ github.sha }}
      run: |
        ./mvnw \
          --batch-mode \
          --settings ./.mvn/github-packages-settings.xml \
          -Dsha1="${GITHUB_SHA}" \
          -Drevision="${REVISION}" \
          -DaltDeploymentRepository="github::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}" \
          deploy
